name: Trello integration
on:
    pull_request:
        types: [opened, edited, closed, reopened, ready_for_review, converted_to_draft]
    issue_comment:
        types: [created, edited]
jobs:
    trello:
        runs-on: ubuntu-latest
        steps:
            - uses: rematocorp/trello-integration-action@v9.6.4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  trello-api-key: ${{ secrets.TRELLO_API_KEY }}
                  trello-auth-token: ${{ secrets.TRELLO_AUTH_TOKEN }}
                  trello-list-id-pr-open: 66e6223fc9a11e1e1cfdcfc1
                  trello-list-id-pr-closed: 66e6225c7d728173b9abdbb1
                  trello-list-id-pr-draft: 66e468761e762a768ddaba31       
                  trello-list-id-pr-changes-requested: 66e6224d7ae778eba4ff0bb3 
                  trello-list-id-pr-approved: 66e62258c8ecf0d39176e2a0
